### ISSUE TITLE
let's improve this recipe (and set a standard for python packages calling julia packages)

### ISSUE THREAD

**Issue by ngam** [conda-forge/pysr-feedstock#38]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This line shouldn't end like that and it useless; the package on anaconda.org doesn't have any of these crazy julia modules being installed: https://anaconda.org/conda-forge/pysr/files

https://github.com/conda-forge/pysr-feedstock/blob/cbf0bb3c7efa0262fe442a4f8495799fc1eb471c/recipe/meta.yaml#L14

If you really want `&& {{ PYTHON }} -c 'import pysr; pysr.install()` you should add it in an activation script.

@ocefpaf, sorry I just saw your question on gitter. I am never there, and usually not very good at instant messaging 😅 it is probably easier to get my attention to something via tag in an open pull request or issue.

Also tagging @isuruf if you have time to look into this with us.

The original message on gitter:

```
Filipe @ocefpaf Aug 06 10:55
Folks, what are the best practices for packaging a Python module that depends on a Julia pkg? @ngam I recall you packaging some Julia/Python stuff, do you have any advice for me?
```

Do you have a specific recipe/package? I am happy to work on it together in staged-recipes! Just tag me or respond here :) 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by MilesCranmer** [comment]
I agree it would be better if the `pysr.install()` ran as part of the conda install. Do you know how to implement that?

**Comment by MilesCranmer** [comment]
The post-link trick sounds like the best bet to me. Happy to try this, let me know when I can get started.

**Comment by MilesCranmer** [comment]
Hm, I'm reading the [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html) on it now and I'm not sure `post-link.sh` is the right strategy: 

> Post-link and pre-unlink scripts should:
> 
> *  Be avoided whenever possible.
> *  Not touch anything other than the files being installed.
> *  Not write anything to stdout or stderr, unless an error occurs.
>  * Not depend on any installed or to-be-installed conda packages.
>  * Depend only on simple system tools such as rm, cp, mv, and ln.

Specifically the last two points. I'm worried if trying to go this route will introduce a variety of other operating system-specific bugs to solve in the future... What do you think?

**Comment by jaimergp** [comment]
Yes, I am not sure about it either. One of the main questions to answer is how deterministic the script can be. Users expect conda packages to be reproducible, so if it has dynamic behaviour, it better be a controlled one. I am not aware of what `pysr.install()` does, but if it has to find Julia dependencies, can we make sure they are always the same versions?

**Comment by MilesCranmer** [comment]
One thing we could do is fix the Manifest.toml file. Otherwise the Julia dependencies will be different every single install. These are bounded by the Project.toml file but those constraints are pretty soft rather than set to specific versions.

**Comment by mkitti** [comment]
Manifest.toml is good, but I'm not sure if that is a good thing for us to distribute. It would be similar to distributing a conda-lock file.

Perhaps it would be useful to tighten the version bounds further?
https://pkgdocs.julialang.org/v1/compatibility/

**Comment by MilesCranmer** [comment]
I guess even if you tighten the version bounds on all the direct dependencies, the dependencies of those dependencies could still change their version. (and this sometimes could result in [distinct behavior](https://discourse.julialang.org/t/github-action-mysteriously-starts-breaking-on-windows/86048) as a function of date the package is installed...). You could add `[compat]` bounds on the entire dependency tree, but then it seems is the same as the Manifest.toml file, no?

**Comment by ocefpaf** [comment]
> I agree it would be better if the `pysr.install()` ran as part of the conda install. Do you know how to implement that?

I'm not so sure. I like the `module.install()`, at least for now, b/c that makes an easy transition to folks who wants to manually install Julia vs those who are packaging in systems like conda-forge, debian, etc. However, I have zero knowledge of Julia packaging and my thoughts here should be taken with a grain of salt.

**Comment by ocefpaf** [comment]
```yaml
 script: {{ PYTHON }} -m pip install . -vv' 
 script: {{ JULIA }} -c 'using Pkg; Pkg.install(".")' 
```

That would be the dream, right?
