### ISSUE TITLE
Unpin numpy as a host-dependency

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pysr-feedstock#83]
By having `>= 1.14` in the host section, this disables our mechanism for building against the oldest supported numpy. This means the recipe will always pull in the newest numpy (currently 1.24), and by the way the numpy C API works, this means the all pysr builds _need_ the newest numpy to run[^1]. 

Effectively, this turns `>=1.14` into `>=1.24` (soon 1.25), which is clearly not the intent. Please have a look at the relevant [section](https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy) in the knowledge base.

[^1]: numpy doesn't bump the relevant [marker](https://github.com/numpy/numpy/blob/v1.25.0rc1/numpy/core/setup_common.py#L52) for every version, but almost.

**Comment by MilesCranmer** [comment]
Thanks. Just to confirm, I should leave the numpy pin in `run` as is?

**Comment by h-vetinari** [comment]
> ~Thanks. Just to confirm, I should leave the numpy pin in `run` as is?~
> 
> Nevermind, I had forgotten the difference but just re-read the docs page.

As the docs explain, you should use `- {{ pin_compatible('numpy') }}` in run (which I don't see in #85)
