### ISSUE TITLE
Do not ever store build artefacts on `main`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pysr-feedstock#86]
This pollutes our azure accounts (and storage allowance) for 2 years with useless stuff. It's fine for debugging a PR, but https://github.com/conda-forge/pysr-feedstock/commit/925d13211796c3a23db694585c3fa91599677b59 should have never been merged to main.

CC @ngam

**Comment by h-vetinari** [comment]
> Also, I was under the impression the artifacts are only stored for ~60 (or less) days just like the logs

That's just for PRs. Logs on main get persisted for 2 years. Checking the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=15111&_a=summary) here, it seems that the artefacts already get deleted before that (not sure based on what mechanism and whether that changed recently - I've never seen what actually happens with artefact persistence on main; I'm just reflecting the clear instructions I've gotten about this, but details aside, it seems like a no-brainer to not store these things pointlessly)

**Comment by MilesCranmer** [comment]
Closed from #85
