### ISSUE TITLE
Set `CONDA_JL_HOME`?

### ISSUE THREAD

**Issue by MilesCranmer** [conda-forge/pysr-feedstock#88]
@ngam @mkitti do we need to set `CONDA_JL_HOME` anywhere? I noticed this part of `Conda.jl`'s README:

> ## Using a pre-existing Conda installation
> To use a pre-existing Conda installation, first create an environment for
> `Conda.jl` and then set the `CONDA_JL_HOME` environment variable to the full
> path of the environment.
> (You have to rebuild `Conda.jl` and many of the packages that use it after this.)
> In Julia, run:
> 
> ```jl
> julia> run(`conda create -n conda_jl python conda`)
> 
> julia> ENV["CONDA_JL_HOME"] = "/path/to/miniconda/envs/conda_jl"  # change this to your path
> 
> pkg> build Conda
> ```

Perhaps we don't, but I was just curious.

**Comment by mkitti** [comment]
We do on activate.sh

```
export CONDA_JL_HOME=$CONDA_PREFIX
``1

**Comment by MilesCranmer** [comment]
Okay, that is great. Thanks!
